//
//  Constants.swift
//  BookManager
//
//  Created by Fai on 26/01/26.
//

import SwiftUI

let SETTINGS_THEME_KEY = "SETTINGS_THEME_KEY"
let DEFAULT_SETTINGS_THEME_VALUE = Theme.Light

let FAVORITE_GRID_COLUMNS_KEY = "FAVORITE_GRID_COLUMNS_KEY"
let FAVORITE_GRID_COLUMNS_KEY_DEFAULT = 2
